package grbl

var errorMessages = map[int]string{
	1:  "Expected command letter",
	2:  "Bad number format",
	3:  "Invalid statement",
	4:  "Negative value",
	5:  "Setting disabled",
	6:  "Step pulse min < 3usec",
	7:  "Settings read fail",
	8:  "Command requires idle state",
	9:  "G-code locked during alarm or jog",
	10: "Soft limits require homing",
	11: "Max characters per line exceeded",
	12: "Max step rate exceeded",
	13: "Safety door detected",
	14: "Startup line too long",
	15: "Jog target exceeds machine travel",
	16: "Jog command missing '=' or has prohibited word",
	17: "Laser mode requires PWM output",
	20: "Unsupported or invalid G-code command",
	21: "More than one command in modal group 0",
	22: "Feed rate not set",
	23: "G-code requires integer value",
	24: "More than one G-code using axis words",
	25: "Repeated G-code word",
	26: "No axis words in command",
	27: "Invalid line number",
	28: "G-code missing required value",
	29: "G59.x work coordinate not supported",
	30: "G53 requires G0 or G1",
	31: "Axis word without commanded motion",
	32: "G2/G3 requires in-plane axis word",
	33: "Motion command targets invalid axis",
	34: "Invalid arc radius",
	35: "G2/G3 requires in-plane offset word",
	36: "Unused value word in block",
	37: "G43.1 offset not on tool length axis",
	38: "Tool number exceeds max",
}

var alarmMessages = map[int]string{
	1:  "Hard limit triggered",
	2:  "Soft limit alarm",
	3:  "Abort during cycle",
	4:  "Probe fail: not in expected initial state",
	5:  "Probe fail: did not contact workpiece",
	6:  "Homing fail: could not clear limit switch",
	7:  "Homing fail: could not find limit switch",
	8:  "Homing fail: limit switch not found within search distance",
	9:  "Homing fail: could not find second switch for auto-squaring",
	10: "EStop triggered",
}
