package gcode

import (
	"fmt"
	"os"
	"strings"
)

// Writer accumulates G-code lines and provides file output.
type Writer struct {
	lines []string
}

func NewWriter() *Writer {
	return &Writer{}
}

func (w *Writer) Add(line string) {
	w.lines = append(w.lines, line)
}

func (w *Writer) Addf(format string, args ...interface{}) {
	w.lines = append(w.lines, fmt.Sprintf(format, args...))
}

func (w *Writer) Comment(text string) {
	w.lines = append(w.lines, "; "+text)
}

func (w *Writer) Blank() {
	w.lines = append(w.lines, "")
}

func (w *Writer) Lines() []string {
	return w.lines
}

func (w *Writer) String() string {
	return strings.Join(w.lines, "\n") + "\n"
}

func (w *Writer) WriteFile(path string) error {
	return os.WriteFile(path, []byte(w.String()), 0644)
}

// Header writes standard G-code preamble.
func (w *Writer) Header(laserMode bool, power float64) {
	w.Comment("Generated by GoLaserCut")
	w.Add("G90 G21")
	w.Add("G17")
	if laserMode {
		w.Add("M4")
	} else {
		w.Add("M3")
	}
	w.Addf("S%.0f", power)
}

// Footer writes standard G-code epilogue.
func (w *Writer) Footer() {
	w.Add("S0")
	w.Add("M5")
	w.Add("G0 X0 Y0")
	w.Add("M2")
}

// Rapid adds a rapid move.
func (w *Writer) Rapid(x, y float64) {
	w.Addf("G0 X%.3f Y%.3f", x, y)
}

// RapidZ adds a rapid Z move.
func (w *Writer) RapidZ(z float64) {
	w.Addf("G0 Z%.3f", z)
}

// LinearMove adds a cutting move with feed rate.
func (w *Writer) LinearMove(x, y, feed float64) {
	w.Addf("G1 X%.3f Y%.3f F%.0f", x, y, feed)
}

// LinearMoveZ adds a cutting move with Z and feed rate.
func (w *Writer) LinearMoveZ(x, y, z, feed float64) {
	w.Addf("G1 X%.3f Y%.3f Z%.3f F%.0f", x, y, z, feed)
}

// SetPower adds an S command.
func (w *Writer) SetPower(s float64) {
	w.Addf("S%.0f", s)
}

// AirAssistOn adds M7 (mist coolant / air assist).
func (w *Writer) AirAssistOn() {
	w.Add("M7")
}

// AirAssistOff adds M9 (coolant off).
func (w *Writer) AirAssistOff() {
	w.Add("M9")
}

// Dwell adds a pause in milliseconds.
func (w *Writer) Dwell(ms float64) {
	w.Addf("G4 P%.1f", ms)
}

// MultiPass wraps a function call in pass markers.
func (w *Writer) MultiPass(passes int, fn func(pass int)) {
	if passes < 1 {
		passes = 1
	}
	for i := 0; i < passes; i++ {
		if passes > 1 {
			w.Blank()
			w.Addf("; pass %d/%d", i+1, passes)
		}
		fn(i)
	}
}

// Count returns the number of lines written.
func (w *Writer) Count() int {
	return len(w.lines)
}
